name: python Workflow

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  check-style:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find Trailing Whitespace
        run: |
          set +e
          lines=$(git grep --cached -In '[[:blank:]]$')
          if [ ! -z "$lines" ]; then
             echo -e "\n The following lines contain trailing whitespace: \n"
             echo -e "${lines}"
             echo -e "\nFailed.\n"
             exit 1
          fi
          exit 0
